package:
  name: nanover-essd
  version: {{ NANOVER_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - nanover-essd-list = nanover.essd.list_cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - netifaces

about:
  home: {{ NANOVER_DOC_URL }}
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: Extremely Simple Service Discovery for NanoVer
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides a service discovery method for finding servers
    running on a local area network.
  doc_url: {{ NANOVER_DOC_URL }}
  dev_url: {{ NANOVER_REPO_URL }}
