package:
  name: nanover-essd
  version: {{ NANOVER_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - netifaces

about:
  home: https://nanover.readthedocs.io
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: Extremely Simple Service Discovery for NanoVer
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides a service discovery method for finding servers
    running on a local area network.
  doc_url: https://nanover.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/nanover-protocol
