image: intangiblerealitieslab/dotnet-conda
stages:
  - test
  - packaging
  - deploy

release:
  stage: deploy
  only:
    - master
    - develop
  artifacts:
    paths:
      - python-libraries
      - csharp-libraries/Narupa.Protocol/bin/Release
  script:
    - ./compile.sh

# triggers a build of the narupa documentation repo. 
trigger_docs_build:
  stage: deploy
  script:
    - "curl -X POST -F token=6ebebef71969e5dd996b5df299bb22 -F ref=master https://gitlab.com/api/v4/projects/11677300/trigger/pipeline"

debug:
  stage: test
  script:
    - ./compile.sh
    - python -m pip install -r python-libraries/requirements.test
    - python -m pytest --cov=narupa python-libraries
    - coverage html
  artifacts:
    paths:
      - htmlcov
      - csharp-libraries/Narupa.Protocol/bin/Release

test_dotnet:
  stage: test
  variables:
    test_path: "csharp-libraries"
  script:
    - "cd $test_path"
    - "dotnet test"

build_conda:
    stage: packaging
    variables:
        build_command: "conda build --prefix-length=100 "
    script:
        # Configure the environment. We need conda-forge to get the science
        # related packages (openmm, ase, mdanalysis)
        - conda config --env --add channels conda-forge
        - conda config --env --add channels omnia
        - conda install conda-build grpcio-tools conda-verify anaconda
        # Compiling the prototypes
        - python python-libraries/narupa-core/setup.py compile_proto --proto-dir=protocol
        # narupa-core must come first as all depends on it
        - $build_command python-libraries/narupa-core/conda
        - $build_command python-libraries/narupa-openmm/conda
        - $build_command python-libraries/narupa-ase/conda
        - $build_command python-libraries/narupa-mdanalysis/conda
        # narupa-server must come last as it depends on everything
        - $build_command python-libraries/narupa-server/conda
        - cp -r /miniconda/conda-bld .
    artifacts:
        paths:
          - conda-bld

upload_conda:
    stage: deploy
    only:
      - feature/conda
    script:
      # The login token may be used by a failed build already. If we are asked
      # if we want it back, we say yes. Hence the echo Y.
      - echo Y | anaconda login --username irl_bot --password $ANACONDA_PASSWORD
      # Anaconda will complain if the given version of a package is already
      # there. Until we have some versionning, we force the upload.
      - anaconda  upload --user irl conda-bld/noarch/narupa-*.tar.bz2 --force
      # Do not fail the build if we cannot logout.
      - anaconda logout || echo "Could not logout. Too bad."
