image: intangiblerealitieslab/dotnet-conda
stages:
  - test
  - deploy

release:
  stage: deploy
  only:
    - master
    - develop
  artifacts:
    paths:
      - python-libraries
      - csharp-libraries/Narupa.Protocol/bin/Release
  script:
    - ./compile.sh
    - dotnet build --configuration Release csharp-libraries/Narupa.Protocol

debug:
  stage: test
  script:
    - ./compile.sh
    - python -m pip install -r python-libraries/requirements.test
    - python -m pytest --cov=narupa python-libraries
    - coverage html
  artifacts:
    paths:
      - htmlcov
