image: intangiblerealitieslab/conda-light
stages:
  - stage1
  - stage2
  - deploy

release:
  image: intangiblerealitieslab/dotnet-conda
  stage: deploy
  only:
    - master
    - develop
  artifacts:
    paths:
      - python-libraries
      - csharp-libraries/Narupa.Protocol/bin/Release
  script:
    - conda install -c conda-forge mpi4py
    - ./compile.sh

# triggers a build of the narupa documentation repo. 
trigger_docs_build:
  stage: deploy
  script:
    - "curl -X POST -F token=${DOCS_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/11677300/trigger/pipeline"

test_python:
  stage: stage2
  before_script:
    - conda install -c omnia -c conda-forge -c ./conda-bld ${PIN_VERSIONS} mpi4py narupa-server
    - python -m pip install -r python-libraries/requirements.test
  script:
    - python -m pytest --cov=narupa python-libraries -n auto -m 'not serial' --junitxml=report_not_serial.xml
    - python -m pytest --cov=narupa --cov-append python-libraries -n0 -m 'serial' --junitxml=report_serial.xml
    - coverage html
  artifacts:
    paths:
      - htmlcov
      - csharp-libraries/Narupa.Protocol/bin/Release
    reports:
      junit:
        - report_not_serial.xml
        - report_serial.xml

test_python_minimum:
  stage: stage2
  before_script:
    - export PIN_VERSIONS='python=3.6 ase=3.19.0'
    - conda install -c omnia -c conda-forge -c ./conda-bld ${PIN_VERSIONS} mpi4py narupa-server
    - python -m pip install -r python-libraries/requirements.test
  script:
    - python -m pytest python-libraries -n auto -m 'not serial' --junitxml=report_not_serial_minimum.xml
    - python -m pytest python-libraries -n0 -m 'serial'' --junitxml=report_serial_minimum.xml
  artifacts:
    reports:
      junit:
        - report_not_serial_minimum.xml
        - report_serial_minimum.xml

test_dotnet:
  image: intangiblerealitieslab/dotnet-conda
  stage: stage1
  variables:
    test_path: "csharp-libraries"
  script:
    - conda install -c conda-forge mpi4py
    - ./compile.sh
    - "cd $test_path"
    - dotnet add package JunitXml.TestLogger
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    reports:
      junit:
        - ./**/*test-result.xml

build_conda:
    stage: stage1
    variables:
        build_command: "conda build --prefix-length=100 --no-test --no-anaconda-upload "
    script:
        # Test that the repo is sane and does not contain superfluous __init__ file
        - bash maintainers/check_extra_init_files.sh
        # We use the number of commits in the branch to set the version number.
        - export NARUPA_BUILD_VERSION="0.1.$(git rev-list --count HEAD)"
        - export NARUPA_LICENSE_PATH="$(readlink -f LICENSE)"
        # Configure the environment. We need conda-forge and omnia to get the
        # science related packages (openmm, ase, mdanalysis)
        - conda config --env --add channels conda-forge
        - conda config --env --add channels omnia
        - conda install conda-build grpcio-tools conda-verify
        # Compiling the prototypes
        - python python-libraries/narupa-core/setup.py compile_proto --proto-dir=protocol
        # The order of the packages is defined by their requirements.
        - |
            $build_command \
              python-libraries/narupa-essd/conda \
              python-libraries/narupa-core/conda \
              python-libraries/narupa-openmm/conda \
              python-libraries/narupa-ase/conda \
              python-libraries/narupa-mdanalysis/conda \
              python-libraries/narupa-lammps/conda \
              python-libraries/narupa-server/conda
        - cp -r /miniconda/conda-bld .
    artifacts:
        paths:
          - conda-bld

upload_conda:
    stage: deploy
    only:
      - master
    script:
      - conda install anaconda
      # The login token may be used by a failed build already. If we are asked
      # if we want it back, we say yes. Hence the echo Y.
      - echo Y | anaconda login --username irl_bot --password $ANACONDA_PASSWORD
      # Anaconda will complain if the given version of a package is already
      # there. Until we have some visioning, we force the upload.
      - anaconda  upload --user irl conda-bld/noarch/narupa-*.tar.bz2 --force
      # Do not fail the build if we cannot logout.
      - anaconda logout || echo "Could not logout. Too bad."
