package:
  name: narupa-server
  version: 0.1.0

build:
  noarch: python
  number: 0

requirements:
  run:
    - narupa-core
    - narupa-openmm
    - narupa-ase
    - narupa-mdanalysis

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ RECIPE_DIR }}/../../../LICENSE
  summary: Python servers for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation is
    virtual reality. This package cause all the python servers to be installed.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
