package:
  name: narupa-openmm
  version: 0.1.0

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm

  run:
    - python
    - narupa-core
    - numpy
    - openmm

about:
  home: narupa.readthedocs.io