package:
  name: narupa-openmm
  version: 0.1.0

source:
  path: ../

build:
  noarch: generic
  number: 0
  entry_points:
    - narupa-omm-server = narupa.openmm.cli:main

requirements:
  build:
    - python >= 3.6.0
    - setuptools
    - openmm

  run:
    - python >= 3.6.0
    - narupa-core
    - numpy
    - openmm

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ RECIPE_DIR }}/../../../LICENSE
  summary: OpenMM server for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation is
    virtual reality. This package provides the OpenMM server for Narupa.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
