name: conda
description: Set conda with caching

runs:
  using: composite
  steps:
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('etc/example-environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniforge-version: latest
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
