package:
  name: nanover-core
  version: {{ os.environ["NANOVER_BUILD_VERSION"] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - nanover-multiplayer = nanover.multiplayer.cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools
    - grpcio-tools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - typing-extensions
    - protobuf
    - grpcio
    - numpy
    - nanover-essd =={{ NANOVER_BUILD_VERSION }}

about:
  home: https://nanover.readthedocs.io
  license: GPL-3
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: Core modules to use the NanoVer python library.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides the core components to write a
    server or a client program in python.
  doc_url: https://nanover.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/nanover-protocol
