package:
  name: nanover-nglview
  version: {{ NANOVER_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - nanover-core =={{ NANOVER_BUILD_VERSION }}
    - numpy
    - mdanalysis
    - nglview

about:
  home: {{ NANOVER_DOC_URL }}
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: NGLView python client for NanoVer.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides a python client that allows the
    user to visualise the molecular system via an NGLView widget in Jupyter
    notebooks or IPython.
  doc_url: {{ NANOVER_DOC_URL }}
  dev_url: {{ NANOVER_REPO_URL }}
