package:
  name: narupa-core
  version: 0.1.0

source:
  path: ../

build:
  noarch: python
  number: 1

requirements:
  build:
    - python >= 3.6.0
    - setuptools
    - grpcio-tools

  run:
    - python >= 3.6.0
    - protobuf
    - grpcio
    - numpy

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ RECIPE_DIR }}/../../../LICENSE
  summary: Core modules to use the Narupa python library.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation is
    virtual reality. This package provides the core components to write a
    server or a client program in python.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
