name: "Notify docs repo to update submodules"

on:
  pull_request:

jobs:
  trigger-submodule-update:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.DOCS_UPDATE_APP_ID }}
          private-key: ${{ secrets.DOCS_UPDATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            nanover-protocol
            nanover-docs
      - name: Trigger submodule update workflow in docs
        env:
          DOCS_UPDATE_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $DOCS_UPDATE_TOKEN" \
            https://api.github.com/repos/IRL2/nanover-docs/actions/workflows/submodules.yml/dispatches \
            -d '{"ref":"main"}'