package:
  name: nanover-openmm
  version: {{ NANOVER_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - nanover-omm-server = nanover.openmm.cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - nanover-core =={{ NANOVER_BUILD_VERSION }}
    - numpy
    - openmm

about:
  home: https://nanover.readthedocs.io
  license: MIT
  license_file: {{ NANOVER_LICENSE_PATH }}
  summary: OpenMM server for NanoVer.
  description: |
    NanoVer is a framework for interactive molecular dynamics simulation is
    virtual reality. This package provides the OpenMM server for NanoVer.
  doc_url: https://nanover.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/nanover-protocol
